### ISSUE TITLE
Issue when using angular-web-component with universal

### ISSUE THREAD

**Issue by r3plica** [Scandit/barcodescanner-sdk-for-web-samples#18] opened 2021-04-04 15:42 UTC
Hi,

I created a new blank angular project and then copied the app.module and app.component from the example and added my license key. when you run `ng serve` it works fine. 

then if you install angular universal `ng add @nguniversal/express-engine` and then run `npm run dev:ssr` it errors out.
I tried installing domino and making sure the window.navigator was set:

```
    const domino = require('domino');
    const fs = require('fs');

    // Use the browser index.html as template for the mock window
    const template = fs
      .readFileSync(join(process.cwd(), 'dist/scandit/browser', 'index.html'))
      .toString();

    const window = domino.createWindow(template);

    global['window'] = window;
    global['navigator'] = window.navigator;
```

But when you run it, it just tells me that there is a reference error: navigator is not defined.
The error is here:

BrowserHelper.userAgentInfo = new ua_parser_js_1.default(navigator.userAgent);

I suspect this is due to angular universal gotchas:

https://github.com/angular/universal/blob/master/docs/gotchas.md

**Comment by Shyiy** [comment] 2021-04-06 05:55
As you correctly mentioned the issue is reported (with a solution) as part of https://github.com/angular/universal/blob/master/docs/gotchas.md#strategy-2-guards
As our library needs to run on the client, you need to make sure it's not invoked on the server side via dependency injection as explained in their guide.

**Comment by ScanditSupport** [comment] 2021-04-06 06:41
@r3plica in case you still have open questions or the issue is not resolved by following the above mentioned guidance, we're happy to help you directly to take your individual setup into account. Please send a request via https://support.scandit.com

Scandit Support

**Closed** 2021-04-06 06:44 UTC

**Comment by r3plica** [comment] 2021-04-06 09:21
Thanks for your reply. Could you post an example of what you think the work around is? I have tried (I believe) everything that is in that document and have not been able to get the application to work.

**Comment by ScanditSupport** [comment] 2021-04-06 18:53
Hi @r3plica 
would you mind providing the codes snippets you've been using for testing via our support portal: https://support.scandit.com/ such that we could look into your particular configuration?

Best regards
Scandit Support
